version: '3.9'

services:
  backend:
    build:
      context: ./Matching
      dockerfile: Dockerfile
    container_name: matching-back
    ports:
      - "8000:8000"
    env_file:
      - ./Matching/.env.production
    restart: always

  frontend:
    build:
      context: ./Front-Matching
      dockerfile: Dockerfile
    container_name: matching-front
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: always
