name: Build and Push Docker Images

on:
  push:
    branches: [ main ]
    paths:
      - '.gitmodules'
      - 'Matching'
      - 'Matching/**'
      - 'Matching/Dockerfile'
      - 'Front-Matching'
      - 'Front-Matching/**'
      - 'Front-Matching/Dockerfile'
      - '.github/workflows/ci-cd.yml'
      - 'docker-compose.yml'

permissions:
  contents: read
  packages: write

concurrency:
  group: ci-cd-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout monorepo + submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.GH_TOKEN }}
          fetch-depth: 0

      - name: Create Vertex service account key file
        run: |
          mkdir -p Matching/keys
          printf '%s' "${{ secrets.VERTEX_SA_JSON }}" > Matching/keys/talentmatch-2-vertex-a82db02697d9.json


      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Backend (Matching)
        uses: docker/build-push-action@v5
        with:
          context: ./Matching
          file: ./Matching/Dockerfile
          push: true
          platforms: linux/amd64
          tags: kaloina/back-matching:latest

      - name: Build & Push Frontend (Front-Matching)
        uses: docker/build-push-action@v5
        with:
          context: ./Front-Matching
          file: ./Front-Matching/Dockerfile
          push: true
          platforms: linux/amd64
          tags: kaloina/front-matching:latest
